# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 16 Pro",                # 6.3" - required for AppStore Connect
    "iPhone 16 Pro Max",            # 6.9" - required for AppStore Connect
    "iPhone SE (3rd generation)",   # 4.7" - required for AppStore Connect
    "iPad Air 11-inch (M2)",        # 11.0" - required for AppStore Connect
    "iPad Air 13-inch (M2)"         # 13.0" - required for AppStore Connect
])

languages([
  "en-US",
  "de-DE"
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
